//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShoppingCartAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class CityMaster
    {
        public string Id { get; set; }
        public string CityName { get; set; }
        public string StateId { get; set; }
        public string PinCode { get; set; }
    }
}
