//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShoppingCartAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderDetail
    {
        public string OrderNo { get; set; }
        public Nullable<System.DateTime> OrderDate { get; set; }
        public string ManufacturerComapany { get; set; }
        public string Address { get; set; }
        public string CityId { get; set; }
        public string MobileNo { get; set; }
        public string PaymentMode { get; set; }
        public Nullable<decimal> Wallet { get; set; }
        public string OnlineDD { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public string DDno { get; set; }
        public Nullable<decimal> DDAmount { get; set; }
        public Nullable<System.DateTime> DDDate { get; set; }
        public string OrderStatus { get; set; }
        public Nullable<System.DateTime> CancelDate { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public Nullable<decimal> TotalAmount { get; set; }
    }
}
