//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShoppingCartAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductRemark
    {
        public string Id { get; set; }
        public string Name { get; set; }
        public string Email { get; set; }
        public Nullable<short> Rating { get; set; }
        public string Review { get; set; }
        public string ProductId { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    }
}
