//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShoppingCartAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserShippingAddress
    {
        public string Id { get; set; }
        public string pincode { get; set; }
        public string Town { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string Name { get; set; }
        public string Address { get; set; }
        public string MobileNo { get; set; }
        public string UserId { get; set; }
        public Nullable<bool> DefaultAddress { get; set; }
    }
}
